# Based on U-Boot from Denx
# Added by Diwel, Rennes, FR
#



LIB	:= $(obj)libspifi_drv_M4.a

all:	$(LIB)

distclean:

#########################################################################

# defines $(obj).depend target
include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
